### ISSUE TITLE
Warning! Could not load config file

### ISSUE THREAD

**Issue by keineAngstvorHans** [joschi27/MMM-flatastic#1]
I only get a blackscreen 

with the errors:

Warning could not load config file. Starting with default configuration. Error found : Cannot find module 'request'

and later 

code:  'Module not found'

any suggestions?

**Comment by keineAngstvorHans** [comment]
One step further 
npm install inside the modules/mmm-flatastic directory solved it
now port is already in use :/

and after reboot 
loading can be seen, but still not working

**Comment by joschi27** [comment]
Sali Hans

Your error might be related to this: https://forum.magicmirror.builders/topic/1490/problems-restarting-magicmirror-port-8080-in-use

It's not something my module is at fault for. You might have started the webserver (that magicmirror starts in the background, do you use pm2?) twice, which would explain the port issues. I believe the module does not connect to a port.

Please keep me updated! I've added the npm install in the readme.

**Comment by keineAngstvorHans** [comment]
thx joschi27 
i guess that was the first error i had. I'll try again soon and keep u updated :) nice projekt btw .

**Comment by joschi27** [comment]
Thank you!

**Comment by keineAngstvorHans** [comment]
After some ongoing testing and full reset, I still haven't made it work, :(. The basics are clear, but could you please help me with the syntax. I'd like to have some clarity about my try-and-error process.

Is it : 
a "apikey"
b "{apikey}"
c 'apikey' 
d "{{apikey}}"

I guess i dont need any brakets at all, am I correct? - like in a or c

**Comment by joschi27** [comment]
Damn! Yep, it's a or c. You could send me a copy of your config and ill take a look (remove the api key though) :)

**Comment by keineAngstvorHans** [comment]
I got it to work now. :) Thanks for your help. The problem was within the api key- weird but today i got a different api key then usual. Maybe i was to bad to write it down correctly :/ . I also get different api keys, depending on the browser i use. This time it worked with "Brave". :) Thanks for all your help and have a great time <3

**Comment by joschi27** [comment]
Oh thats interesting with the api keys! Thanks for the info. No worries, u too! :)
